export const LOGIN = 'LOGIN';
export const ADD_USER =  'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE';
export const FORM_SUBMITION_STATUS ='FORM_SUBMITION_STATUS' ;